version: '3.7'

services:

  main:
    image: bitroid/bitroidjenkins:${TAG:-latest}
    ports:
      - 8080:8080
      - 50000:50000
    secrets:
      - jenkins-user
      - jenkins-pass

secrets:
  jenkins-user:
    file: ./jenuser
  jenkins-pass:
    file: ./jenpass
